#!/usr/bin/env tsx
/**
 * Build-time metadata collector.
 * Writes src/content/build-metadata.ts and src/content/fallback-commit.ts.
 * See specs/001-the-cursor/plan.md "Build-time metadata" and task 025.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

function defaultDeps(cwd: string): CollectDeps {
  return {
    runner: (cmd) => execSync(cmd, { cwd, encoding: "utf8" }).trim(),
    listDir: (dir) => readdirSync(dir),
    listDirEntries: (dir) =>
      readdirSync(dir, { withFileTypes: true }).map((e) => ({
        name: e.name,
        isDir: e.isDirectory(),
      })),
    readFile: (file) => readFileSync(file, "utf8"),
  };
}

export interface BuildMetadata {
  sha: string;
  shortSha: string;
  specCount: number;
  taskCount: number;
  lieCount: 0;
}

export interface FallbackCommit {
  sha: string;
  shortSha: string;
  message: string;
}

export interface CollectDeps {
  runner: (cmd: string) => string;
  listDir: (dir: string) => string[];
  listDirEntries: (dir: string) => { name: string; isDir: boolean }[];
  readFile: (file: string) => string;
}

function walkTaskFiles(dir: string, deps: CollectDeps): string[] {
  const entries = deps.listDirEntries(dir);
  const results: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDir) {
      results.push(...walkTaskFiles(full, deps));
    } else if (entry.name === "tasks.md") {
      results.push(full);
    }
  }
  return results;
}

export function collect(
  cwd: string = process.cwd(),
  deps: CollectDeps = defaultDeps(cwd),
): { metadata: BuildMetadata; fallback: FallbackCommit } {
  const sha = deps.runner("git rev-parse HEAD");
  const shortSha = sha.slice(0, 7);

  const specsDir = path.join(cwd, "specs");
  const specCount = deps
    .listDir(specsDir)
    .filter((name) => /^\d{3}-/.test(name)).length;

  const taskFiles = walkTaskFiles(specsDir, deps);
  let taskCount = 0;
  const taskLineRegex = /^- \[[x ]\]/gm;
  for (const file of taskFiles) {
    const contents = deps.readFile(file);
    const matches = contents.match(taskLineRegex);
    taskCount += matches ? matches.length : 0;
  }

  const lastCommit = deps
    .runner('git log -1 --pretty=format:"%h|%s"')
    .replace(/^"|"$/g, "");
  const [fallbackShort, ...messageParts] = lastCommit.split("|");
  const message = messageParts.join("|");

  return {
    metadata: { sha, shortSha, specCount, taskCount, lieCount: 0 },
    fallback: { sha, shortSha: fallbackShort, message },
  };
}

function formatFile(name: string, typeName: string, value: unknown): string {
  return `// AUTO-GENERATED by scripts/collect-build-metadata.ts — do not edit by hand.
// Regenerated on every build via the "prebuild" npm script.

export const ${name} = ${JSON.stringify(value, null, 2)} as const;

export type ${typeName} = typeof ${name};
`;
}

function main(): void {
  const cwd = process.cwd();
  const { metadata, fallback } = collect(cwd);

  const outDir = path.join(cwd, "src", "content");
  mkdirSync(outDir, { recursive: true });

  writeFileSync(
    path.join(outDir, "build-metadata.ts"),
    formatFile("BUILD_METADATA", "BuildMetadata", metadata),
  );
  writeFileSync(
    path.join(outDir, "fallback-commit.ts"),
    formatFile("FALLBACK_COMMIT", "FallbackCommit", fallback),
  );

  console.log(
    `[collect-build-metadata] sha=${metadata.shortSha} specs=${metadata.specCount} tasks=${metadata.taskCount}`,
  );
}

// Only run main() when executed as a script, not when imported in tests.
const isDirectRun =
  typeof process !== "undefined" &&
  process.argv[1] &&
  path
    .resolve(process.argv[1])
    .endsWith(path.join("scripts", "collect-build-metadata.ts"));

if (isDirectRun) {
  main();
}
